name: Daily Script Execution

on:
  schedule:
    # Ejecuta todos los días a las 4:40 AM UTC (equivalente a 1:40 AM en Argentina)
    - cron: '40 4 * * *'
  workflow_dispatch:  # Esto te permite ejecutar el cron manualmente desde GitHub si lo deseas

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python path/to/your/script.py
