name: Enviar Mensaje Diario

on:
  # schedule:
  #   - cron: '30 10 * * *'  # Ejecuta todos los días a las 7:30 AM (Argentina) / 10:30 AM UTC
  schedule:
    - cron: '50 13 * * *'  # Ejecuta todos los días a las 10:50 AM (Argentina) / 13:50 PM UTC
  workflow_dispatch:  # Permite ejecución manual

permissions:
  contents: read
  actions: write

jobs:
  send-message:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify environment variables
      run: |
        echo "Checking environment variables..."
        if [ -z "${{ secrets.OPENROUTER_API_KEY }}" ]; then
          echo "Error: OPENROUTER_API_KEY is not set"
          exit 1
        fi
        if [ -z "${{ secrets.TWILIO_SID }}" ]; then
          echo "Error: TWILIO_SID is not set"
          exit 1
        fi
        if [ -z "${{ secrets.TWILIO_AUTH_TOKEN }}" ]; then
          echo "Error: TWILIO_AUTH_TOKEN is not set"
          exit 1
        fi
        if [ -z "${{ secrets.TO_WHATSAPP }}" ]; then
          echo "Error: TO_WHATSAPP is not set"
          exit 1
        fi
        if [ -z "${{ secrets.TWILIO_TEMPLATE_SID }}" ]; then
          echo "Error: TWILIO_TEMPLATE_SID is not set"
          exit 1
        fi
        echo "All required environment variables are set"
    
    - name: Run script
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        TWILIO_SID: ${{ secrets.TWILIO_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TO_WHATSAPP: ${{ secrets.TO_WHATSAPP }}
        TWILIO_TEMPLATE_SID: ${{ secrets.TWILIO_TEMPLATE_SID }}
        SITE_URL: ${{ secrets.SITE_URL }}
        SITE_NAME: ${{ secrets.SITE_NAME }}
      run: |
        echo "Starting script execution at $(date)"
        echo "Current timezone: $(date +%Z)"
        echo "UTC time: $(date -u)"
        python main.py
        if [ $? -ne 0 ]; then
          echo "Error: Script execution failed"
          exit 1
        fi
        echo "Script execution completed successfully at $(date)" 